config/routes.rb
Rails.application.routes.draw do
	require 'api'

  get 'welcome/about'

  resources :phones

  resources :contacts

  resources :departments do
    member do
      get :contacts
    end
  end

  resources :companies do
    member do
      get :departments, :contacts
      post :set_company_departments
    end
  end

	mount CompanyContact::API => '/'

  root 'welcome#index'

end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :company
  belongs_to :department, foreign_key: :parent_id
  has_many :contacts
  validates_presence_of :name
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy, :contacts]

  # GET /departments
  # GET /departments.json
  def index
    @q = Department.ransack(params[:q])
    @departments = @q.result.page(params[:page])
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
    @companies = Company.all
    @departments = []
  end

  # GET /departments/1/edit
  def edit
    @companies = Company.all
    if @department.company
      @departments = @department.company.departments 
    else
      @departments = []
    end
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)
    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        @companies = Company.all
        @departments = []
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        @companies = Company.all
        @departments = []
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def contacts
    @contacts = @department.contacts
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :company_id, :parent_id)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<div class="form-group">
<%= form_for(@department, html: {class: "form-inline"}) do |f| %>
  <div class="form-group">
    <% if @department.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

        <ul>
          <% @department.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name, "部门名称" %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :company_id, "公司" %><br>
      <%= f.select :company_id, options_from_collection_for_select(@companies, "id", "name", (@department.company.id rescue nil)), {prompt: "请选择部门所在公司"}, onchange: "set_company_departments(this.value)", class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :parent_id, "上级部门" %><br>
      <%= f.select :parent_id, options_from_collection_for_select(@departments, "id", "name", (@department.department.id rescue nil)), {prompt: "请选择部门的上级部门"}, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit "提交", class: "btn btn-default" %>
    </div>
  </div>
<% end %>
</div>
<script type="text/javascript">
  function set_company_departments(value){
    if(value != ""){
      $.ajax({
        type: "POST",
        url: "/companies/" + value + "/set_company_departments",
        data: 'text',
        success: function(data){
          $('#department_parent_id').html(data);
        }
      })
    }
    else {
      $('#department_parent_id').html('<option value="">请选择部门的上级部门</option>');
    }
  }
</script>

app/views/departments/contacts.html.erb
<p id="notice"><%= notice %></p>
<div class="btn-group">
  <%= link_to '返回', :back, class: "btn btn-default" %>
</div>

<h3>公司部门联系人</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>联系人</th>
      <th>手机号码</th>
      <th>公司名称</th>
      <th>部门</th>
      <th colspan="2">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |c| %>
      <tr>
        <td><%= c.name %></td>
        <td><%= c.phones.map {|p| p.phone_number}.join(",") rescue "" %></td>
        <td><%= c.company.name %></td>
        <td><%= c.department.name rescue '没有部门' %></td>
        <td><%= link_to '查看', contact_path(c) %></td>
        <td><%= link_to '删除', c, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/departments/edit.html.erb
<div class="btn-group">
  <%= link_to '查看', @department, class: "btn btn-default" %>
  <%= link_to '返回', :back, class: "btn btn-default" %>
</div>
<h3>编辑组织架构</h3>

<%= render 'form' %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h3>公司部门列表</h3>
<div class="form-group">
  <%= search_form_for @q, class: "form-inline" do |f| %>
    <div class="form-group">
      <%= f.label :name_cont, :部门 %>
      <%= f.search_field :name_cont, class: "form-control" %>
      <%= f.submit "查询", class: "btn btn-default" %>
    </div>
  <% end %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>部门名称</th>
      <th>公司名称</th>
      <th>上级部门</th>
      <th colspan="3">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
				<td><%= department.company.name rescue "部门还不属于某个公司" %></td>
        <td><%= department.department.name rescue "无上级部门" %></td>
        <td><%= link_to '查看部门', department %></td>
        <td><%= link_to '查看部门联系人', contacts_department_path(department) %></td>
        <td><%= link_to '删除', department, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建部门', new_department_path, class: "btn btn-default" %>
<br>
<%= paginate @departments %>

app/views/departments/new.html.erb
<div class="btn-group">
  <%= link_to '返回', departments_path, class: "btn btn-default" %>
</div>
<h3>新建部门</h3>

<%= render 'form' %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>
<div class="btn-group">
  <%= link_to '编辑', edit_department_path(@department), class: "btn btn-default" %>
  <%= link_to '返回', departments_path, class: "btn btn-default" %>
</div>
<p>
  <strong>部门名称:</strong>
  <%= @department.name %>
</p>

<p>
  <strong>公司:</strong>
	<%= @department.company.name rescue "部门还不属于某个公司" %>
</p>

<p>
  <strong>上级部门:</strong>
  <%= @department.department.name rescue "无上级部门"%>
</p>

<p>
  <strong>公司所有部门:</strong>
  <%= @department.company.departments.map {|d| d.name}.join(",") rescue nil %>
</p>