config/routes.rb
Rails.application.routes.draw do
	require 'api'

  get 'welcome/about'

  resources :phones

  resources :contacts

  resources :departments do
    member do
      get :contacts
    end
  end

  resources :companies do
    member do
      get :departments, :contacts
      post :set_company_departments
    end
  end

	mount CompanyContact::API => '/'

  root 'welcome#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :company
  belongs_to :department
	has_many :phones
  validates_presence_of :name
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
		@q = Contact.ransack(params[:q])
    @contacts = @q.result.page(params[:page])
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @companies = Company.all
    @departments = []
  end

  # GET /contacts/1/edit
  def edit
    @companies = Company.all
    @departments = @contact.company.departments
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :company_id, :department_id)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<div class="form-group">
<%= form_for(@contact, html: {class: "form-inline"}) do |f| %>
  <div class="form-group">
    <% if @contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

        <ul>
          <% @contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name, "联系人" %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :company_id, "联系人所在公司" %><br>
      <%= f.select :company_id, options_from_collection_for_select(@companies, "id", "name", (@contact.company.id rescue nil)), {prompt: "请选择联系人所在公司"}, onchange: "set_company_departments(this.value)", class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :department_id, "联系人所在公司部门" %><br>
      <%= f.select :department_id, options_from_collection_for_select(@departments, "id", "name", (@contact.department.id rescue nil)), {prompt: "请选择联系人所在部门"}, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit "提交", class: "btn btn-default" %>
    </div>
  <% end %>
  </div>
</div>
<script type="text/javascript">
function set_company_departments(value){
  if(value != ""){
    $.ajax({
      type: "POST",
      url: "/companies/" + value + "/set_company_departments",
      data: 'text',
      success: function(data){
        $('#contact_department_id').html(data);
      }
    })
  }
  else {
    $('#contact_department_id').html('<option value="">请选择联系人所在部门</option>');
  }
}
</script>

app/views/contacts/edit.html.erb
<div class="btn-group">
  <%= link_to '显示', @contact, class: "btn btn-default" %>
  <%= link_to '返回', contacts_path, class: "btn btn-default" %>
</div>
<h3>编辑联系人</h3>

<%= render 'form' %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h3>联系人列表</h3>
<div class="form-group">
	<%= search_form_for @q, class: "form-inline" do |f| %>
		<div class="form-group">
			<%= f.label :name_cont, :联系人 %>
			<%= f.search_field :name_cont, class: "form-control" %>
			<%= f.submit "查询", class: "btn btn-default" %>
		</div>
	<% end %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>联系人</th>
      <th>手机号码</th>
      <th>联系人所在公司</th>
      <th>联系人所在公司部门</th>
      <th colspan="2">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.phones.map {|p| p.phone_number}.join(",") rescue "" %></td>
				<td><%= contact.company.name rescue "联系人还没有所在公司" %></td>
				<td><%= contact.department.name rescue "联第人还没有所在公司部门" %></td>
        <td><%= link_to '查看', contact %></td>
        <td><%= link_to '删除', contact, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建联系人', new_contact_path, class: "btn btn-default" %>
<br>
<%= paginate @contacts %>

app/views/contacts/new.html.erb
<div class="btn-group">
  <%= link_to '返回', contacts_path, class: "btn btn-default" %>
</div>
<h3>新建联系人</h3>

<%= render 'form' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="btn-group">
  <%= link_to '编辑', edit_contact_path(@contact), class: "btn btn-default" %>
  <%= link_to '返回', contacts_path, class: "btn btn-default" %>
</div>
<p>
  <strong>联系人:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>联系人手机号码:</strong>
  <%= @contact.phones.map {|p| p.phone_number}.join(",") %>
</p>

<p>
  <strong>联系人所在公司:</strong>
	<%= @contact.company.name rescue "联系人还没有所在公司" %>
</p>

<p>
  <strong>联系人所在公司部门:</strong>
	<%= @contact.department.name rescue "联系人还没有所在公司部门" %>
</p>