config/routes.rb
Rails.application.routes.draw do
	require 'api'

  get 'welcome/about'

  resources :phones

  resources :contacts

  resources :departments do
    member do
      get :contacts
    end
  end

  resources :companies do
    member do
      get :departments, :contacts
      post :set_company_departments
    end
  end

	mount CompanyContact::API => '/'

  root 'welcome#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :departments
  has_many :contacts
  validates_presence_of :name
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy, :departments, :contacts, :set_company_departments]

  # GET /companies
  # GET /companies.json
  def index
    @q = Company.ransack(params[:q])
    @companies = @q.result.page(params[:page])
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def departments
    @departments = @company.departments
  end
  
  def contacts
    @contacts = @company.contacts
  end

  def set_company_departments
    options = ""
    @departments = @company.departments
    @departments.each do |d|
      options << "<option value=#{d.id}>#{d.name}</option>"
    end
    render text: options
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="form-group">
<%= form_for(@company, html: {class: "form-inline"}) do |f| %>
  <div class="form-group">
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% @company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "公司名", class: "required" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "提交", class: "btn btn-default" %>
  </div>
  </div>
<% end %>
</div>

app/views/companies/contacts.html.erb
<p id="notice"><%= notice %></p>
<div class="btn-group">
<%= link_to '返回', :back, class: "btn btn-default" %>
</div>
<h3>公司联系人</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>联系人</th>
      <th>手机号码</th>
      <th>公司名称</th>
      <th>部门</th>
      <th colspan="2">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |c| %>
      <tr>
        <td><%= c.name %></td>
        <td><%= c.phones.map {|p| p.phone_number}.join(",") rescue "" %></td>
        <td><%= c.company.name %></td>
        <td><%= c.department.name rescue '没有部门' %></td>
        <td><%= link_to '编辑', edit_contact_path(c) %></td>
        <td><%= link_to '删除', c, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/departments.html.erb
<p id="notice"><%= notice %></p>
<div class="btn-group">
  <%= link_to '返回', :back, class: "btn btn-default" %>
</div>

<h3>公司组织架构</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>公司名称</th>
      <th>部门</th>
      <th>上级部门</th>
      <th colspan="2">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |d| %>
      <tr>
        <td><%= d.company.name %></td>
        <td><%= d.name %></td>
        <td><%= d.department.name rescue '无上级部门' %></td>
        <td><%= link_to '编辑', edit_department_path(d) %></td>
        <td><%= link_to '删除', d, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/edit.html.erb
<div class="btn-group">
  <%= link_to '查看', @company, class: "btn btn-default" %>
  <%= link_to '返回', :back, class: "btn btn-default" %>
</div>
<h3>编辑公司</h3>

<%= render 'form' %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h3>公司列表</h3>
<div class="form-group">
  <%= search_form_for @q, class: "form-inline" do |f| %>
    <div class="form-group">
      <%= f.label :name_cont, :公司名 %>
      <%= f.search_field :name_cont, class: "form-control" %>
      <%= f.submit "查询", class: "btn btn-default" %>
    </div>
  <% end %>
</div>

<table class="table table-bordered">
	<thead>
		<tr>
			<th>公司名称</th>
			<th colspan="4">操作</th>
		</tr>
	</thead>

	<tbody>
		<% @companies.each do |company| %>
			<tr>
				<td><%= company.name %></td>
				<td><%= link_to '查看公司', company %></td>
				<td><%= link_to '查看组织架构', departments_company_path(company) %></td>
				<td><%= link_to '查看联系人', contacts_company_path(company) %></td>
				<td><%= link_to '删除', company, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to '新建公司', new_company_path, class: "btn btn-default" %>
<br>
<%= paginate @companies %>

app/views/companies/new.html.erb
<div class="btn-group">
  <%= link_to '返回', companies_path, class: "btn btn-default" %>
</div>
<h3>新建公司</h3>

<%= render 'form' %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<div class="btn-group">
  <%= link_to '编辑', edit_company_path(@company), class: "btn btn-default" %>
  <%= link_to '返回', companies_path, class: "btn btn-default" %>
</div>

<p>
  <strong>公司名:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>公司部门:</strong>
  <%= @company.departments.map {|d| d.name}.join(",") %>
</p>

<p>
  <strong>公司联系人及联系方式:</strong>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>联系人</th>
        <th>手机号码</th>
      </tr>
    </thead>

    <tbody>
      <% @company.contacts.each do |c| %>
        <tr>
          <td><%= c.name %></td>
          <td><%= c.phones.map {|p| p.phone_number}.join(",") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</p>