config/routes.rb
Rails.application.routes.draw do
	require 'api'

  get 'welcome/about'

  resources :phones

  resources :contacts

  resources :departments do
    member do
      get :contacts
    end
  end

  resources :companies do
    member do
      get :departments, :contacts
      post :set_company_departments
    end
  end

	mount CompanyContact::API => '/'

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>公司通讯录</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand hidden-sm" href="http://www.net263.com/" target="_blank">上海二六三通信</a>
      </div>
      <div class="navbar-collapse collapse" role="navigation">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to "首页", root_path %>
          </li>
          <li class="dropdown hidden-sm hidden-md">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">菜单<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "公司", companies_path, target: "_blank" %>
              </li>
              <li>
                <%= link_to "组织架构", departments_path, target: "_blank" %>
              </li>
              <li>
                <%= link_to "联系人", contacts_path, target: "_blank" %>
              </li>
            </ul>
          </li>
          <li>
            <%= link_to "公司", companies_path %>
          </li>
          <li>
            <%= link_to "组织架构", departments_path %>
          </li>
          <li>
            <%= link_to "联系人", contacts_path %>
          </li>
          <li>
            <%= link_to "手机号码", phones_path %>
          </li>
        </ul>
        </ul>
        </ul>
        <ul class="nav navbar-nav navbar-right hidden-sm">
          <li>
            <%= link_to "关于", welcome_about_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="yield-content container">
    <%= yield %>
  </div>
</body>
</html>